apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: khmndr/department:latest  
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres   #host should be same as connstring in code 
            - name: DB_USER
              value: postgres
            - name: DB_PASS
              value: postgres123
            - name: DB_NAME
              value: mydatabase
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  
